### ISSUE TITLE
Prevent model saving in disk

### ISSUE THREAD

**Issue by talhaanwarch** [awslabs/autogluon#1071]
Is there a way to avoid saving of model in the disk? I checked the [docs ](https://github.com/awslabs/autogluon/blob/e618bf9caf83d7f86c9cd4d86caaaeb7f1d7f16c/tabular/src/autogluon/tabular/predictor/predictor.py#L74)but if the `path` to set to None instead of not saving, it saved it to a time-stamped based folder.

**Comment by Innixma** [comment]
Not at present. This is to simplify the code and avoid nasty out-of-memory errors. If the amount of disk usage is the problem, the upcoming v0.2.0 reduces Tabular's disk usage by ~10x+ in many cases.

**Comment by Innixma** [comment]
Closing as wontfix for now. Adding this functionality adds a great deal of code complexity for not much benefit. Please re-open if you can highlight a use-case where saving to disk is not an option.

**Comment by NumberPigeon** [comment]
Hi @Innixma ,

I met the same problem here. My use case is to build a distributed ML pipeline system, and all the in-middle steps will be pickled and saved by the system. Here I use Autogluon as a good operator, but since it will auto-save the model after the fit process, I have to delete it by my self (or if there is a better way, like a custom predictor base on tablular and omit the saving process, please tell me :)

I mean, it's ok to use disk before the final training process, but I do not want to save the model by Autogluon, and prefer to deal with it myself. So I think in this case, giving a flag to disable model save would be good.
