### ISSUE TITLE
TinyML and Model Deployment

### ISSUE THREAD

**Issue by seekingdeep** [awslabs/autogluon#1138]
.

**Comment by Innixma** [comment]
Hi @seekingdeep, I was planning to respond to this issue but saw that you just deleted the content. Is there a reason why?

**Comment by seekingdeep** [comment]
@Innixma hi,
i noticed that you had a lot on your plate. Believe me my intentions were good.

**Comment by Innixma** [comment]
No worries!

While I don't have time to dive deeply into this topic, the general idea is reasonable. A pre-req for this to work is that no data-preprocessing is necessary by AutoGluon, so that the raw data can be directly inputted to the tree model. This is somewhat challenging but can be done if the user knows how to make sure their data is valid prior to inference.

Doing this with AutoGluon's ensemble is somewhat impractical in terms of the coding complexity. I'd rather they used `predictor.distill()` to distill the ensemble into a single model such as XGBoost, Random Forest, etc., and then apply whatever conversion code is necessary to get the optimized splitting script.

If you'd like to contribute this functionality, the main work is to take a given AutoGluon model, such as the [XGBoostModel](https://auto.gluon.ai/stable/_modules/autogluon/tabular/models/xgboost/xgboost_model.html#XGBoostModel), and add a method to it which converts it to this optimized format you are referring to.

**Comment by seekingdeep** [comment]
@Innixma there is a library dealing with this task called treelite
 https://treelite.readthedocs.io/en/latest/
https://github.com/dmlc/treelite

https://github.com/neo-ai/neo-ai-dlr

**Comment by seekingdeep** [comment]
ok
