### ISSUE TITLE
Spark parallel memory warnings

### ISSUE THREAD

**Issue by noamanemobidata** [awslabs/autogluon#1145]
Hi!

I'm running TabularPredictor inside a Pandas function for each group of a spark dataFrame:

 ```

schema_2= StructType([
  StructField('ds', DateType()),
  StructField('yhat', IntegerType()),
  StructField('ID', StringType())
  
])

def autog(df: pd.DataFrame) -> pd.DataFrame:
  
  
  predictor = TabularPredictor(label="QTE",
                                   problem_type="regression") \
  .fit(train_data=df,
       excluded_model_types =["NN","KNN"],
       auto_stack=True,
       presets='best_quality',
       time_limit=5400)
   ....

  return prediction_df




(sparkdf
           .groupBy('GROUP_ID') # each group contain aprox 600K rows
           .applyInPandas(autog, schema=schema_2)
          )
```

I'm using 2 workers of 64G each, but some models are skipped : 
```
Warning: Early stopped GBM model prior to optimal result to avoid OOM error. Please increase available memory to avoid subpar model quality.
	Warning: Exception caused LightGBMXT_BAG_L1 to fail during training... Skipping this model.
```

is there another solution (other than increasing the memory) to have better quality models ?
Thank you

**Comment by noamanemobidata** [comment]
In `.fit` I excluded NN models but it seems that autogluon is tring to fit  `NeuralNetFastAI`  :
`Time limit exceeded... Skipping NeuralNetFastAI_BAG_L1.`

**Comment by Innixma** [comment]
I would recommend training AutoGluon predictor's sequentially rather than in parallel if possible, unless you have a spark cluster such that each worker is training a singular predictor in isolation. A single predictor tries to use as much resources as possible, so training them in parallel on the same machine would not be helpful as they are trying to use all cores. I'm unsure exactly how spark does this if there are more than 2 GROUP_ID's but only 2 workers, but if it tries to train 10 predictors on each worker at the same time, this probably isn't ideal (each predictor would train 10x slower due to fighting for the same resources, while taking a total of 10x the usual memory).

Given that LightGBM rarely runs into memory issues, I'm pretty sure it is this parallel training that is causing the problems.

Regarding the NN models, there are two NN models: `NN` and `FASTAI`, you'll need to add `FASTAI` to your excluded models list.

You may want to try with a smaller sample of your data this code and see if the problem still persists, 600k rows shouldn't cause issues in most cases, but if you have many unique GROUP_IDs, this might be the reason.
