### ISSUE TITLE
How to custom activation function?

### ISSUE THREAD

**Issue by 2010hexi** [awslabs/autogluon#1178]
If i want to use my own activation function, how to extend it on autogluon ?
is there any tutorial or instructions?

**Comment by Innixma** [comment]
We will need more information in order to help. Could you provide a code example or a description of the problem and the functionality that solves it? Activation functions are specific to neural networks, and we have many different neural networks in AutoGluon for a variety of tasks (vision, text, tabular). Each of them has their own hyperparameters which can be specified by the user, likely including the activation function.

**Comment by 2010hexi** [comment]
> We will need more information in order to help. Could you provide a code example or a description of the problem and the functionality that solves it? Activation functions are specific to neural networks, and we have many different neural networks in AutoGluon for a variety of tasks (vision, text, tabular). Each of them has their own hyperparameters which can be specified by the user, likely including the activation function.

Hi Innixma, thank you for your reply.
AutoGluon is an excellent tool for AI.  Now I do not have detail information about the specified activation function.
I am wondering if there is such an extension to custom user self design activation function to apply into the autogluon to see if could improve performance or not . Just like Torch, it provides such an option for users custom their own activation function.

**Comment by Innixma** [comment]
Unless more users request the ability to specify custom activation functions or it is shown that custom activation functions can provide significant score improvements, we will probably not support them due to code complexity.

In general, I doubt specifying a custom activation function is the level of detail you want to be performing in AutoGluon. You can specify from a variety of different activations however, such as with TabularPredictor via

`hyperparameters={'NN': {'activation': 'tanh'}}`

Given the options `['relu', 'softrelu', 'tanh', 'softsign']`, with `'relu'` being the default.

Closing for now.
