### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'Categorical'

### ISSUE THREAD

**Issue by talhaanwarch** [awslabs/autogluon#1179]
I think after PR #1164 I can use 'medium_quality_faster_inference' preset because previously I am getting error #1141. But now I am getting a new error. 
Version: 0.2.1b20210612
Colab notebook
https://colab.research.google.com/drive/1SshDbvdCSzvRpxDc5qRsvxM03NfKEUqp?usp=sharing

**Comment by Innixma** [comment]
Thanks yet again for highlighting the issue, this is very valuable!

@zhreshold The error is because there is code that is trying to ensure the batch size is valid via:

```
bs = min(config.get('batch_size', 16), len(train_data))
```

However, this is done when `config['batch_size']` can still be represented as a search space i.e. `Categorical[64, 128]`.

Therefore, whenever a search space is specified for `batch_size`, predictor will crash.

This means every preset option crashes except for `medium_quality_faster_train` which does not search.

This bug was introduced in #1113 and was not caught by our unit tests, @zhreshold could you add unit tests to test at least the two `medium_quality` settings with simplified hyperparameters (such as `'epochs': 2`)? We will also need to move the batch size check internally or make it smarter so it checks each option in search space and corrects/removes them if they are invalid.
