### ISSUE TITLE
Reproducibility of experiments

### ISSUE THREAD

**Issue by danski3456** [awslabs/autogluon#1194]
Hi, Is there any way to fix the seed of the whole training procedure, so that results are reproducible? 

Apparently there was some sort of seed for the cross validation part in some older documentation, but it does not seem to work anymore.

**Comment by Innixma** [comment]
I believe that everything is already reproducible if HPO is disabled and the FASTAI neural network model is disabled. Cross-validation splits are deterministic and reproducible given the same data.

FASTAI is non-deterministic during training for performance reasons, and we have not implemented seeded HPO. Ensure that time_limit is set to None as well so that time does not impact the training process.

In general, we don't plan to keep results reproducible, as generally the difference between seeds is fairly negligible and the coding complexity to ensure this is too high.
