### ISSUE TITLE
Handle memory issue?

### ISSUE THREAD

**Issue by talhaanwarch** [awslabs/autogluon#1250]
I have a large data, that does not fit into ram while training, though I can load it in ram. But once I start training, I got oom error. Any idea how to resolve the issue? Is there some thing called batch training?

**Comment by Innixma** [comment]
Could you clarify the modality? (Image, Text, Tabular). Also, please specify if you are using pre-release, system information, and script code + logs where possible.

**Comment by off99555** [comment]
I also have a very big dataset. Is there a best practice of training big dataset?

**Comment by smolix** [comment]
Please provide some more details. There are quite a few ways of dealing with a large dataset but it depends on the type. You might want to use specific data loaders for images or text.

**Comment by off99555** [comment]
The OP probably will not answer any time. So what about tabular dataset (CSV)? How can you use specific data loader on that?
Any example code?

**Comment by Innixma** [comment]
> The OP probably will not answer any time. So what about tabular dataset (CSV)? How can you use specific data loader on that?
> Any example code?

Re Tabular, if you are talking truly very large datasets (no way to fit in memory even by using a machine that has 200+ GB of memory), then you will want to downsample until it does fit in memory.

To make life easier, consider pre-processing the data outside of AutoGluon so it is taking minimal memory when passing to AG (turn string categoricals to numbers, drop unnecessary columns, use uint8 instead of int64, float32 instead of float64, etc.)

AG can handle data that is 50 GB in size if you properly preprocess it and have a big enough machine, but AG does not train in batches, all data you want to train with must be in memory at once. Batch training is not functionality we plan to support in the near-term, as it is highly complex to integrate into a framework which trains many different kinds of models.

**Comment by off99555** [comment]
Roger that @Innixma I think I'll have to go with the downsizing approach and bigger machine.

**Comment by talhaanwarch** [comment]
sorry, i forget to mention, changing to float16 from float64 helped me
