### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by zuliani99** [awslabs/autogluon#1269]
I'm running AutoGluon with these options:
```
predictor = TabularPredictor(label=target, problem_type=pt).fit(
      train_data=X_train,
      time_limit=options['time']*60,
      presets=['best_quality'],
      auto_stack=True
)
```
And then after a few minutes my application got this exception which forces the execution of autogluon:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    code = _serve_one(child_r, fds,
  File "/usr/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    code = _serve_one(child_r, fds,
  File "/usr/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
```

**Comment by Innixma** [comment]
Please provide the full stack trac, run logs, system information, and `pip freeze` output otherwise I won't be able to help identify the issue.

**Comment by zuliani99** [comment]
The stack trace that I was able to capture is what I posted before.

System Information:
- Ubuntu 20.04.2 LTS
- Ram: 16 GBs
- Python 3.8.10 64-bit
- Virtual environment
- AutoGluon 0.2.0

These are my requirements, there are so may because I'm doing a benchmark between five AutoML algorithms
[requirements.txt](https://github.com/awslabs/autogluon/files/6976603/requirements.txt)

**Comment by Innixma** [comment]
If you are benchmarking automl systems, you may want to consider using AutoMLBenchmark (https://github.com/openml/automlbenchmark)

It will be a lot cleaner than trying to get everything working in one virtual environment. That is probably why you are having issues in the first place.

If you still continue to have issues, please reproduce with a fresh virtual environment with only AutoGluon installed, and provide the full code used to produce the error. For now I will close as I suspect the issue is due to the complex environment setup you have.
