### ISSUE TITLE
Where is the legend of TabularDataset(feature_types) in the documentation

### ISSUE THREAD

**Issue by chijan-nh** [awslabs/autogluon#1318]
I' d like to specify the types of the features in a table data for each column.
In the documentation, that can be realized by setting `feature_types` argument to a dict: [ref](https://auto.gluon.ai/stable/api/autogluon.task.html#autogluon.tabular.TabularDataset).
However, the legend of the types which autogluon recognizes is not described in the above ref.
I guess the dict is like the following:
```python
feature_types = {
  "col_name1": "int",
  "col_name2": "categorical",
  "col_name3": "numerical",
  "col_name4": "text", ...
}
```
but the settable items are not mentioned.

Where can I find the solution?
Also, I would like you to specify that solution in the above document.

**Comment by Innixma** [comment]
Thanks for opening an issue!

The documentation you referenced does not seem to make any mention of `feature_types`, so I'm unsure where you are getting that information. For generic dtypes, use pandas API as TabularDataset is a pandas DataFrame.

Specifying custom feature types can be done with `FeatureMetadata` (Also in the doc you linked).

For an example, see the Tabular-Text-Image tutorial where we specify a custom image path column type:
https://auto.gluon.ai/stable/tutorials/tabular_prediction/tabular-multimodal.html#constructing-the-featuremetadata

The available types are listed here:
https://github.com/awslabs/autogluon/blob/master/core/src/autogluon/core/features/types.py

It is recommended in most cases to let AutoGluon determine the dtypes instead of specifying them explicitly (unless you are editing raw dtypes with pandas, which is fine). AG automatically detects text and categorical features for example.

The available dtypes and how to set them is currently not documented on the website, so we can probably improve this in v0.4 release. I plan to also add a feature preprocessing related tutorial, which should help explain this functionality.

**Comment by chijan-nh** [comment]
Maybe I referred an old documentation since I saw `feature_types` argument in the doc before #1317 is resolved (old docs are removed) ...

> It is recommended in most cases to let AutoGluon determine the dtypes instead of specifying them explicitly (unless you are editing raw dtypes with pandas, which is fine). AG automatically detects text and categorical features for example.

In my case, I'd like to compare the results when I changed the type annotation of the string variable column which can be interpreted as  a text as well as a categorical feature.

According to the following quotation from https://arxiv.org/pdf/2003.06505.pdf page 3 line 12, my understanding is that Autogluon infers a string as a text when it consists three or more words. 

```
We consider text features to
be columns of mostly unique strings, which on average contain more than 3 non-adjacent whitespace characters.
```

I will use this to separate cases.

> The available dtypes and how to set them is currently not documented on the website, so we can probably improve this in v0.4 release. I plan to also add a feature preprocessing related tutorial, which should help explain this functionality.

Thanks! I'm looking forward to seeing the next release and being provided a function to set feature types.

Thank you for your kind replying.
