### ISSUE TITLE
Text features overwhelming numerical/categorical features

### ISSUE THREAD

**Issue by SaffronWolf** [awslabs/autogluon#1372]
For a dataset containing text features along with numerical and categorical features, TabularPredictor produces a disproportionately high number of features from text compared to other types. Features extracted from text are typically 20-30 times more in number than other type of features. These would mean numerical/categorical features would have little say in training and inference and results would be completely dominated by text features. Is there a way to overcome this? (Apologies if am misunderstanding something).

![image](https://user-images.githubusercontent.com/58913015/140799079-7c2fd36b-4bb2-4d0f-bf87-488b52a66a7c.png)

**Comment by Innixma** [comment]
Just because more features are related to text does not mean that those features dominate how the models learn. This is very specific to the particular model implementations and the predictive signal of each feature.

You could instead preprocess the data yourself and then pass that to AutoGluon and see if it does better, however the current technique performs quite well: https://openreview.net/pdf?id=OHAIVOOl7Vl

**Comment by SaffronWolf** [comment]
That is an excellent paper. Thanks a lot.

**Comment by Innixma** [comment]
If you are interested, the full paper (Accepted at Neurips 2021) was just now made available on arxiv: https://arxiv.org/pdf/2111.02705.pdf
