### ISSUE TITLE
Cannot find the notebook "SHAP with AutoGluon-Tabular and Categorical Features"

### ISSUE THREAD

**Issue by mfeurer** [awslabs/autogluon#1373]
This might be a stupid question. The [FAQ](https://auto.gluon.ai/dev/tutorials/tabular_prediction/tabular-faq.html#how-can-i-use-autogluon-for-interpretability) refers to an example "SHAP with AutoGluon-Tabular and Categorical Features". However, I cannot find it in the examples folder. Could you please provide the link and maybe also put it into the notebook?

**Comment by Innixma** [comment]
Thanks for raising this to our attention!

@jwmueller it appears that the notebook with that name does not exist. Was it renamed? We should update our docs to indicate the proper location.

**Comment by jwmueller** [comment]
@mfeurer Sorry this notebook was renamed in the examples folder and it's simply the one called: **SHAP with AutoGluon-Tabular.ipynb**

Name is updated in PR: https://github.com/awslabs/autogluon/pull/1379

**Comment by mfeurer** [comment]
Thanks a lot for the answer :)

**Comment by HazelSCUT** [comment]
Hello everyone, I want to use the SHAP to calculate the importance of each input to the target. I followed the example (SHAP with AutoGluon-Tabular Diabetes regression.ipynb), but it could not work. The whole codes are the following:
![image](https://user-images.githubusercontent.com/61641190/206858795-62f7981f-0cc2-46d6-86c2-303cc3969ff7.png)
![image](https://user-images.githubusercontent.com/61641190/206858820-c81dc5f8-6a2e-4d90-baa6-46d17ee429fa.png)
![image](https://user-images.githubusercontent.com/61641190/206858836-506cdd7e-4b42-4ade-bb92-378482ffcd91.png)
After training and testing  the model, the bug was appearing when I used the shap:
![image](https://user-images.githubusercontent.com/61641190/206858912-18322836-f599-4bb4-b6f6-6a61bf484af0.png)
![image](https://user-images.githubusercontent.com/61641190/206858941-097ebf00-9569-4c32-b97f-fee4ba5fccf1.png)

I don't know how to solve such a problem. Or could you please provide me with an easier code to get it?

Thanks!
