### ISSUE TITLE
[v0.4] Specify real core count to LightGBM

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#1440]
Currently, we use all cores for training LightGBM, but LightGBM can train faster with using only real physical cores.

According to LightGBM docs: https://lightgbm.readthedocs.io/en/latest/Parameters.html#num_threads

> for the best speed, set this to the number of real CPU cores, not the number of threads (most CPUs use hyper-threading to generate 2 threads per CPU core)

```
num_threads = psutil.cpu_count(logical=False)
```

instead of:

```
num_threads = psutil.cpu_count()
```

**Comment by willsmithorg** [comment]
Not all Intel CPUs implement hyperthreading with 2 logical cores per physical core (although most do).
To be sure, use
```
psutil.cpu_count(logical=False)
```

**Comment by Innixma** [comment]
> Not all Intel CPUs implement hyperthreading with 2 logical cores per physical core (although most do).
> 
> To get the definitive number of physical cores, use
> 
> ```
> psutil.cpu_count(logical=False)
> ```

Great point! I've updated the original message to indicate this.

**Comment by willsmithorg** [comment]
Long term it may be worth benchmarking this for pcores <= cores <= vcores, not just the two extremes.

The underlying confusion is that hyperthreading is mostly hype, and increases performance by "[up to 30%](https://www.intel.co.uk/content/www/uk/en/gaming/resources/hyper-threading.html)" (Intel's own words).   Since the OS reports vcores not pcores, the cloud providers all used vcores as the metric to define cloud VMs, now everybody thinks they are getting vcores.  But really they're getting pcores * (1+"up to 30%").  E.g. a m5.8xlarge with 32 vcpus is a 16 pcore machine.

I've benchmarked myself in previous work, and found that a setting of around 1.2 * pcores often works best, so that if any pcores are blocking on memory/IO, there's enough compute-intensive work to keep them all fully loaded.  Setting cores = vcores is too high and just causes context switching - as you're finding switching from vcores to pcores.

With most models in AG now set to use cores = pcores, I often see in 'top' that the CPU utilization on my 2-socket, 32 pcores, 64 vcores machine is around 2800%.  I believe 3200% would mean that the CPU is fully utilized.  So there may be a gain from setting cores = pcores * 1.2.

Here's a reasonable reference for how hyperthreading works.
https://medium.com/@ITsolutions/will-hyper-threading-improve-processing-performance-15cba11add74
