### ISSUE TITLE
cannot import name 'PROTOCOL_TLS' from 'urllib3.util.ssl_' 

### ISSUE THREAD

**Issue by oneluxyou** [awslabs/autogluon#1532]
cannot import name 'PROTOCOL_TLS' from 'urllib3.util.ssl_' (/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py)

**Comment by Innixma** [comment]
This is too vague to assist with atm. Please provide the full stack trace, AG version, code and logs, preferably with a reproducible example (such as via Google Colab).

**Comment by nateprewitt** [comment]
@Innixma This was likely related to a Lambda deployment which has since been reverted. The underlying issue is with using new versions of Boto3 with incompatible versions of urllib3. Boto3 requires urllib3>1.25.4 (preferably >1.25.9) due to security issues with older versions of the library. If an environment is created with these older versions, some operations will not behave as expected, leading to the above error during import time.

**Comment by Innixma** [comment]
@nateprewitt would it be sufficient to limit AutoGluon's allowed boto3 and urllib3 versions to more recent releases or is this purely on your team's side to resolve and it isn't a problem with AutoGluon?

**Comment by nateprewitt** [comment]
I'm not terribly familiar with autogluon's typical installation environment. It appears you're specifying requirements [here](https://github.com/awslabs/autogluon/blob/51b20c4a18de148b4f06b384e56b102c86727153/common/setup.py#L23), which is fine. I couldn't find any pins for urllib3. `pip` will typically handle this for users, but in the specific case of Lambda, some users who were bundling their own older copy of urllib3 hit issues.

I'm not sure there's any actions to be taken, I was just correlating a cause with the time this issue was opened.

**Comment by Innixma** [comment]
Got it, thanks! Will close for now as it seems to be related to a environment setup outside of the control of AutoGluon. If anyone can make recommendations for specific version mins to packages, we can consider adding to AG install logic.
