### ISSUE TITLE
How does AutoGluon select/ensemble models?

### ISSUE THREAD

**Issue by GaoyangLiu** [awslabs/autogluon#1855]
Thanks for the brilliant work. 

I trained AutoGluon on my dataset, and the result is:
![leaderboard](https://user-images.githubusercontent.com/22510136/174805212-b8b71207-82da-4aa7-993c-815b470d6f40.png)

According to Figure 2 in [[2003.06505] AutoGluon-Tabular: Robust and Accurate AutoML for Structured Data](https://arxiv.org/abs/2003.06505), I thought all base models (there are 11 base models) were used to get the WeightedEnsemble_L2. 
<img src="https://user-images.githubusercontent.com/22510136/174799471-c4ddd4a0-ff80-4536-b60f-220cf609e624.png" width="500">

However, with `predictor.plot_ensemble_model()`, got:
<img src="https://user-images.githubusercontent.com/22510136/174805249-a8aca9c8-4891-4e53-afd3-b00d78d08db1.png" width="500">
I am confused about:

1. How does AutoGluon select base models? Only these four base models are selected to get WeightedEnsemble_L2 in my case?
2. Each base model adds an additional feature to concatenate with the input, and there is a weighting (linear) layer before the output. Because the input dimension of the weighting (linear) layer is fixed, should the number of base models be fixed?
4. Is the pred_time_val sum of all base learners and the last weighting layer?

**Comment by Innixma** [comment]
1. All models are considered, but those that get weight=0 are not included in the final ensemble.
2. Medium Quality (the default, which is what you trained) doesn't do multi-layer stacking. Try the more powerful presets to incorporate multi-layer stacking for much stronger results: https://auto.gluon.ai/stable/tutorials/tabular_prediction/tabular-quickstart.html#presets . As to your question, "Because the input dimension of the weighting (linear) layer is fixed, should the number of base models be fixed?": The input dimension for Weighted Ensemble is always the same as the number of base models that feed into it.
3. Yes

**Comment by GaoyangLiu** [comment]
Thank you so much for your reply. It helps a lot. Could explain more about:

How AuotoGluon selects models? Could it be better to use all base models (not just four), since I do not give the time limit?

**Comment by Innixma** [comment]
It uses all base models, and the ones that get 0 weight after training of the weighted ensemble can be dropped, which is what happens.

**Comment by alfa14290** [comment]
In the picture weighted_ensemble L2 is autgluon StackerEnsembleModel or WeightedEnsembleModel?

**Comment by Eungyu212** [comment]
I am curious about the criteria for selecting base models in the StackerEnsembleModel.
Is the fitting process carried out using all models created in the lower layer?
