### ISSUE TITLE
Issue in the bagging and stacking

### ISSUE THREAD

**Issue by veager** [awslabs/autogluon#2122]
Hi developers, 

I found some unexpected results with the bagging and stacking.

I pass the argument `auto_stack=True`  to `predictor.fit()` and then the stacking levels is set 2 (`num_stack_levels=2`) and number of folds is set 8 (`num_bag_folds=8`). Finally, it outputs the following models:

```python
'CatBoost_BAG_L1'
'CatBoost_BAG_L2'
'ExtraTreesEntr_BAG_L1'
'ExtraTreesEntr_BAG_L2'
'ExtraTreesGini_BAG_L1'
'ExtraTreesGini_BAG_L2'
'KNeighborsDist_BAG_L1'
'KNeighborsUnif_BAG_L1'
'LightGBMLarge_BAG_L1'
'LightGBMLarge_BAG_L2'
'LightGBMXT_BAG_L1'
'LightGBMXT_BAG_L2'
'LightGBM_BAG_L1'
'LightGBM_BAG_L2'
'NeuralNetFastAI_BAG_L1'
'NeuralNetFastAI_BAG_L2'
'NeuralNetTorch_BAG_L1'
'NeuralNetTorch_BAG_L2'
'RandomForestEntr_BAG_L1'
'RandomForestEntr_BAG_L2'
'RandomForestGini_BAG_L1'
'RandomForestGini_BAG_L2'
'XGBoost_BAG_L1'
'XGBoost_BAG_L2'
'WeightedEnsemble_L2'
'WeightedEnsemble_L3'
```

Here comes two issues about that:

- The first one is that "KNeighbors" model seems not be used for the Stacking Layer 2, since I **did't** find `KNeighborsDist_BAG_L2` and `KNeighborsDist_BAG_L2`.

- The other one is that not all models are trained by the k-fold strategy. I found only "CatBoost", "XGBoost", "LightGBM", and "NeuralNet" have 8 trained models (S1F1, S1F2, ..., S1F8).  Other models, such "ExtraTrees", "RandomForest", etc , only have one trained model (only have S1F1)

I would like to know how such strategy determined and if I could specify such two arguments for each base models?

Thank you very much!

**Comment by Innixma** [comment]
The settings are like this because they work best in practice on average across a wide range of datasets. RF, XT, and KNN only fit 1 model because of an optimization trick.

To bag all models:

`predictor.fit(..., ag_args_ensemble={'use_child_oof': False})`

To get KNN to be used in layer 2 (you probably don't want to do this):

`predictor.fit(..., ag_args={'valid_stacker': True})`

You can also apply these arguments to the model specific configs if you want 1 RF to be bagged and another to not be.

**Comment by veager** [comment]
That works. Thanks you, Innixma!
