### ISSUE TITLE
Tabular row weight support

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#33]
Add support for row-wise weights in a similar fashion to LightGBM:

https://lightgbm.readthedocs.io/en/latest/Parameters.html#weight_column

We can have a dedicated weight column that is checked for presence such as '__weight', and potentially give the user the option to specify the column in the call to learner init.

With this column we would additionally need to add support for weight in all objective functions and models.

**Comment by kmedved** [comment]
Thanks for this very intriguing library. i wanted to check if there was any update on allowing `sample_weights` for tabular regression problems? Sample weight support is core functionality of every major tabular machine learning library (AutoML and otherwise), e.g., sklearn, xgboost, catboost, lightgbm, ngboost, TPot, H2O, etc... It would be a major enhancement to add support.

Sample weight support is an essential part of many types of analysis (anytime you have multiple observations rolled up already, or when sensors capture multiple observations simultaneously). I work with a lot of sports data as well, and sample weights are an essential part of functionally all analyses.

Thanks again for releasing this library - looking forward to using it!

**Comment by Innixma** [comment]
Hi @kmedved,

Thanks for your interest! This is on our roadmap and we intend to add support for row weights by the end of the year and will notify in this issue when progress has been made.

Best,
Nick

**Comment by kmedved** [comment]
Thanks @Innixma - that's great to hear. This is a very impressive looking library - I'm getting excellent results on my data in limited testing so far, and am excited to deploy it into production.

**Comment by jamescolless** [comment]
Any updates on this? Sample weights are critical in regression problems when you care more about getting certain predictions right than others! As kmedved pointed out this is already implemented in all the other major ML libraries!

**Comment by Innixma** [comment]
Row weight support is planned for our next release (0.1) which is scheduled for release in December.

**Comment by Venge42** [comment]
Any update on this one or the 0.1 release?

**Comment by Innixma** [comment]
v0.1 release has been shifted to February 2021 to allow for more polishing. Row weight support is a stretch goal for v0.1 and will be a high priority follow-up if it doesn't make the v0.1 release.

**Comment by Venge42** [comment]
> v0.1 release has been shifted to February 2021 to allow for more polishing. Row weight support is a stretch goal for v0.1 and will be a high priority follow-up if it doesn't make the v0.1 release.

Great! Thank's for the update. Desperately waiting for it... :)

Thanks for the great work, guys!

**Comment by Innixma** [comment]
sample_weight support is now in PR: #942

**Comment by kmedved** [comment]
Exciting! Thanks @Innixma

**Comment by Innixma** [comment]
#942 has been merged, and this feature should be available in the pre-release on Monday.
