### ISSUE TITLE
Issue with f1 eval_metric and net.evaluate_predictions

### ISSUE THREAD

**Issue by austinmw** [awslabs/autogluon#381]
On a tabular binary classification problem ("yes"/"no" labels rather than 0/1). I'm able to run `net.evaluate_predictions` successfully with `eval_metric='accuracy'`, but when I switch to `eval_metric='f1'`, and rerun evaluate_predictions, I get an sklearn error:

`pos_label=1 is not a valid label: array(['no', 'yes'], dtype='<U3')`

Not sure if this needs to be fixed since I could probably just map no/yes to 0/1, but figured I'd mention it.

**Comment by Innixma** [comment]
This is likely because evaluate_predictions takes in the prediction values after they were converted to the external user representation, but does not convert them to the internal representation before doing evaluations. This should be fixed by converting the inputs to internal representation through self._learner.label_cleaner inside evaluate_predictions()

@jwmueller Can you take a look and see if you can fix?

**Comment by jwmueller** [comment]
Thanks for pointing out this issue.  It should be fixed in this PR:  https://github.com/awslabs/autogluon/pull/387

Note that in the meantime before this PR is merged, you can just do the following as long as the label column is still present in your test_data Dataframe:
```
predictor = task.fit(..., eval_metric = 'f1')
f1 = predictor.evaluate(test_data)
```

**Comment by jwmueller** [comment]
PR has been merged.
