### ISSUE TITLE
Loading models built under past versions

### ISSUE THREAD

**Issue by brianverk** [awslabs/autogluon#467]
Not sure if this is a common issue between models, but I was use 0.0.6, came across an error that made me update to 0.0.9, but then realized I couldnt load my saved models in the directory using task.load() in 0.0.9. I worked around the issue, but wanted to still call this out to hopefully get fixed for future versions.

**Comment by Innixma** [comment]
Great comment! At present, AutoGluon is undergoing major changes to the underlying model code between versions as we are still very early in the development process and are continually refining and adding functionality. Because of this, it is very difficult to make meaningful changes without also making models incompatible between versions. For example, between 0.0.6 and 0.0.9, the entire backend code that stores and accesses models was overhauled.

In future, once development has stabilized, we can consider adding support for models trained with older versions of AutoGluon. For now, I would suggest storing your models with information that indicates which version they were trained with to ensure you are using the proper version to load them. 0.0.6 was broken due to sklearn updating to 0.23 causing skopt to fail to import. To continue using 0.0.6, downgrade sklearn to 0.22 or wait for skopt to update with a fix: https://github.com/scikit-optimize/scikit-optimize/pull/904

**Comment by brianverk** [comment]
Thanks for the response!
