### ISSUE TITLE
num_bagging_folds & stack_ensemble_levels

### ISSUE THREAD

**Issue by diff7** [awslabs/autogluon#573]
Hi, thank you for awesome work.

I can't figure out library's behaviour.

Let's say we have 
1. **num_bagging_folds = k**, it means we train k models on k subsamples from our dataset.
2. then if **stack_ensemble_levels>=1** we stack these models. 
3. and if  **stack_ensemble_levels=0** we choose the best one from step 1.

My confusion comes from the fact when 
**num_bagging_folds = k**
**stack_ensemble_levels=0**

in print statements I see for example "RandomForestClassifier_STACKER_l0", also what l0 means and when does it take other values?

Thank you!

**Comment by Innixma** [comment]
Good question!

l0 stacker models are not true stack models, they are bagged ensembles. However, because AutoGluon's stack ensemble inherits from bagged ensemble, it is simpler in our code logic to consider all bagged ensembles as stack ensembles. (A bagged stack ensemble with no base models is equivalent to a bagged ensemble).

l0 = stack layer 0, these are the original base models.
l1 = stack layer 1 (takes original base models as additional input)
l2 = stack layer 2 (able to take any l<2 models as additional input)
li = stack layer i (able to take any l<i models as additional input)

You can find extensive info about each stacker/bagged model through `predictor.info()`.

If anyone in the community wants to recommend ways to make this clearer without removing any existing functionality, please respond in this thread. Code contributions are also welcome!

**Comment by diff7** [comment]
Great, thank you!

You have a lot of questions glad to see people has  interest in your project.
