### ISSUE TITLE
How to save the text classification model?

### ISSUE THREAD

**Issue by sugspi** [awslabs/autogluon#583]
Hi, 

The class of TextClassificationPredictor is not yet implemented save and load function.
Do you have any workaround way?

Thank you very much for your help.

**Comment by jwmueller** [comment]
Apologies this hasn't been added because we're in the process of overhauling the current text classification module with major improvements (that will produce better models and be much more feature-complete).

While it's not optimal, for now you can try `pickle`:  https://wiki.python.org/moin/UsingPickle
applied to the `classifier` returned by fit.

A better approach could be as follows:
```
from autogluon import TextClassification as task
predictor = task.fit(...)
predictor.model.export('FILE1')
predictor.model = None
pickle.dump(predictor, open('FILE2', 'wb'))
# Reload:
from mxnet import gluon
predictor = pickle.load(open('FILE2', 'rb'))
predictor.model = gluon.nn.SymbolBlock.imports("FILE1-symbol.json", ['data'], "FILE1-0001.params")
```
for details & more options see: https://mxnet.apache.org/versions/1.6/api/python/docs/tutorials/packages/gluon/blocks/save_load_params.html

**Comment by sugspi** [comment]
Thanks to your help,
I could save and load the pickle file to use `cloudpickle`.

```

import cloudpickle
cloudpickle.dump(predictor, open('FILE1', 'wb'))
import pickle
predictor = pickle.load(open('FILE1', 'rb'))
```

Thank you very much again.
