### ISSUE TITLE
Question about when tabular NN EmbedNet will support hybridize

### ISSUE THREAD

**Issue by yusharon** [awslabs/autogluon#624]
Hi 
I have a general question about is there any plan that tabular neural network model will support Hybridize? (There's a TODO in the [nn model](https://github.com/awslabs/autogluon/blob/master/autogluon/utils/tabular/ml/models/tabular_nn/embednet.py#L68))
Can you also help me understand what is the difficulty of not having EmbedNet as a hybridizeBlock? I am still pretty new to MxNet and AutoGluon. Thanks!

**Comment by jwmueller** [comment]
The issue lies in the use of multiple embedding layers, one per categorical feature. This requires indexing just the data from each feature, which can also be done in a hybridized network as well:  https://mxnet.apache.org/versions/1.6/api/python/docs/tutorials/packages/gluon/blocks/hybridize.html#Indexing

But the resulting hybridized implementation was uglier and actually slower than the current NN-code in my preliminary experiments.  If you experiment with hybridization and find a strategy that consistently speeds up the NN, please feel free to contribute a Pull Request!

**Comment by yusharon** [comment]
Got it. thanks for the explanation and context. Will look into this.
