### ISSUE TITLE
TextSpecialFeatureGenerator post_drop_dulicatesd default True

### ISSUE THREAD

**Issue by j2schmit** [awslabs/autogluon#949]
https://github.com/awslabs/autogluon/blob/63fa1da164a3243de214a84067bbfa7d5f89fc51/features/src/autogluon/features/generators/text_special.py#L30

The default value for post_drop_duplicates is True, but for large datasets this activity seems to take a lot of time. Is there a recommended pythonic way to set this as False?

**Comment by Innixma** [comment]
Refer to this example of creating custom feature generators: https://github.com/awslabs/autogluon/blob/master/examples/tabular/example_custom_feature_generator.py

You would need to specify a `feature_generator = PipelineFeatureGenerator(...)` and pass it into `predictor.fit(..., feature_generator)`

Since you'd be using [PipelineFeatureGenerator](https://auto.gluon.ai/dev/api/autogluon.features.html#pipelinefeaturegenerator), you would have full control over all init args of all feature generators used, including [TextSpecialFeatureGenerator](https://auto.gluon.ai/dev/api/autogluon.features.html#textspecialfeaturegenerator). Unfortunately this is a bit involved in order to change one boolean from True to False, but this is because of the vast amount of options available in the feature generators. If you have any ideas for how to make this process (of changing any parameter of any generator) simpler, feel free to propose a solution.

Alternatively, you could update inplace the default AutoMLPipelineFeatureGenerator(), but the code would be brittle if anything changed in future:

```
from autogluon.features.generators import AutoMLPipelineFeatureGenerator, TextSpecialFeatureGenerator
feature_generator = AutoMLPipelineFeatureGenerator()
# Replace the default TextSpecialFeatureGenerator with a custom TextSpecialFeatureGenerator
feature_generator.generators[2][3] = TextSpecialFeatureGenerator(post_drop_duplicates=False)
```

As a question, how large of data do you have (rows and total size in MB), and how long is post_drop_duplicates taking to compute? I would suspect that ngram generation would take more time than drop_duplicates.

**Comment by Innixma** [comment]
I decided to look into this, and I found a way to heavily optimize the DropDuplicatesFeatureGenerator, now it should be 10x-1000x+ faster once this PR is merged: #950

I believe once this optimization is merged, you shouldn't need to disable duplicate dropping.

**Comment by j2schmit** [comment]
Thanks for the quick fix Nick. To answer your question there are around 31M rows around 1 GB (this is already heavily downsampled). The Ngrams went reasonably quick  around 700s (memory constraints limited the vectorizer vocab size). Prior to your fix, drop duplicates hadn't finished after 12 hours of runtime.

**Comment by Innixma** [comment]
Good to know, we haven't thoroughly explored datasets that are beyond 5M rows (especially true for datasets with text in them), so any feedback you have on the experience/further difficulties would be very valuable to improving our support for large datasets. Likely some issues (such as the DropDuplicates issue), only appear with large datasets that are outside of our typical benchmarking.

For instance, I suspect KNN, RF, and XT models will be completely unusable / too slow to be worthwhile, which could inform  us in terms of automatically deactivating them at certain thresholds.
